version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    volumes:
      - ./server:/usr/src/server
      - /usr/src/server/node_modules
      - /usr/src/server/api
    env_file:
      - ./server/.env
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/client
      - /usr/src/client/node_modules
      - /usr/src/client/.next
    env_file:
      - ./client/.env
    depends_on:
      - server
